# -*- coding: utf-8 -*-
"""
200 个常见蔬菜类食材列表
格式: (中文名, 英文文件名)
- 中文名用于拼接百度百科 URL
- 英文文件名用于命名 txt 文件
"""

VEGETABLES = [
    # ==================== 叶菜类 ====================
    ("大白菜", "chinese_cabbage"),
    ("小白菜", "bok_choy"),
    ("菠菜", "spinach"),
    ("生菜", "lettuce"),
    ("油麦菜", "indian_lettuce"),
    ("空心菜", "water_spinach"),
    ("芹菜", "celery"),
    ("韭菜", "chinese_chives"),
    ("茼蒿", "crown_daisy"),
    ("苋菜", "amaranth"),
    ("油菜", "rapeseed_greens"),
    ("芥菜", "mustard_greens"),
    ("荠菜", "shepherds_purse"),
    ("木耳菜", "malabar_spinach"),
    ("苦菊", "endive"),
    ("娃娃菜", "baby_cabbage"),
    ("奶白菜", "milky_cabbage"),
    ("菜心", "choy_sum"),
    ("芥蓝", "chinese_broccoli"),
    ("甘蓝", "cabbage"),
    ("紫甘蓝", "red_cabbage"),
    ("罗马生菜", "romaine_lettuce"),
    ("冰草", "ice_plant"),
    ("马齿苋", "purslane"),
    ("蕹菜", "water_morning_glory"),
    ("芝麻菜", "arugula"),
    ("豆瓣菜", "watercress"),
    ("香菜", "coriander"),
    ("紫苏", "perilla"),
    ("薄荷", "mint"),
    ("茴香", "fennel"),
    ("蒲公英", "dandelion"),
    ("鱼腥草", "houttuynia"),
    ("枸杞叶", "goji_leaves"),
    ("红薯叶", "sweet_potato_leaves"),
    ("芦蒿", "reed_herb"),
    ("水芹", "water_celery"),
    ("藜蒿", "seleng_wormwood"),
    ("菊花脑", "chrysanthemum_greens"),
    ("田七叶", "panax_leaves"),

    # ==================== 根茎类 ====================
    ("土豆", "potato"),
    ("红薯", "sweet_potato"),
    ("山药", "chinese_yam"),
    ("芋头", "taro"),
    ("莲藕", "lotus_root"),
    ("白萝卜", "white_radish"),
    ("胡萝卜", "carrot"),
    ("红萝卜", "red_radish"),
    ("生姜", "ginger"),
    ("大蒜", "garlic"),
    ("洋葱", "onion"),
    ("大葱", "green_onion"),
    ("小葱", "shallot"),
    ("蒜苔", "garlic_sprouts"),
    ("蒜苗", "garlic_shoots"),
    ("韭黄", "yellow_chives"),
    ("竹笋", "bamboo_shoot"),
    ("春笋", "spring_bamboo_shoot"),
    ("冬笋", "winter_bamboo_shoot"),
    ("芦笋", "asparagus"),
    ("茭白", "water_bamboo"),
    ("慈姑", "arrowhead"),
    ("荸荠", "water_chestnut"),
    ("牛蒡", "burdock"),
    ("山葵", "wasabi"),
    ("魔芋", "konjac"),
    ("凉薯", "jicama"),
    ("葛根", "kudzu_root"),
    ("百合", "lily_bulb"),
    ("菱角", "water_caltrop"),
    ("雪莲果", "yacon"),
    ("紫薯", "purple_sweet_potato"),

    # ==================== 瓜果类 ====================
    ("黄瓜", "cucumber"),
    ("南瓜", "pumpkin"),
    ("冬瓜", "winter_melon"),
    ("丝瓜", "loofah"),
    ("苦瓜", "bitter_melon"),
    ("西葫芦", "zucchini"),
    ("佛手瓜", "chayote"),
    ("瓠瓜", "bottle_gourd"),
    ("蛇瓜", "snake_gourd"),
    ("节瓜", "hairy_gourd"),

    # ==================== 茄果类 ====================
    ("番茄", "tomato"),
    ("茄子", "eggplant"),
    ("辣椒", "chili_pepper"),
    ("青椒", "green_pepper"),
    ("甜椒", "bell_pepper"),
    ("彩椒", "colored_pepper"),
    ("朝天椒", "facing_heaven_pepper"),
    ("小米椒", "millet_pepper"),
    ("秋葵", "okra"),
    ("灯笼椒", "lantern_pepper"),
    ("尖椒", "pointed_pepper"),
    ("螺丝椒", "spiral_pepper"),
    ("线椒", "line_pepper"),
    ("圣女果", "cherry_tomato"),

    # ==================== 豆类 ====================
    ("黄豆", "soybean"),
    ("绿豆", "mung_bean"),
    ("红豆", "red_bean"),
    ("黑豆", "black_bean"),
    ("豌豆", "pea"),
    ("毛豆", "edamame"),
    ("四季豆", "green_bean"),
    ("豇豆", "cowpea"),
    ("蚕豆", "broad_bean"),
    ("扁豆", "hyacinth_bean"),
    ("荷兰豆", "snow_pea"),
    ("刀豆", "sword_bean"),
    ("豆芽", "bean_sprouts"),
    ("黄豆芽", "soybean_sprouts"),
    ("绿豆芽", "mung_bean_sprouts"),

    # ==================== 菌菇类 ====================
    ("香菇", "shiitake"),
    ("平菇", "oyster_mushroom"),
    ("金针菇", "enoki"),
    ("杏鲍菇", "king_oyster_mushroom"),
    ("白玉菇", "white_beech_mushroom"),
    ("蟹味菇", "brown_beech_mushroom"),
    ("茶树菇", "tea_tree_mushroom"),
    ("口蘑", "button_mushroom"),
    ("草菇", "straw_mushroom"),
    ("猴头菇", "lions_mane_mushroom"),
    ("竹荪", "bamboo_fungus"),
    ("松茸", "matsutake"),
    ("鸡枞菌", "termite_mushroom"),
    ("牛肝菌", "porcini"),
    ("黑木耳", "black_fungus"),
    ("白木耳", "white_fungus"),
    ("银耳", "silver_ear_fungus"),
    ("毛木耳", "wood_ear"),
    ("羊肚菌", "morel"),
    ("鸡油菌", "chanterelle"),

    # ==================== 花菜类 ====================
    ("花椰菜", "cauliflower"),
    ("西兰花", "broccoli"),
    ("黄花菜", "day_lily"),
    ("韭菜花", "chive_blossoms"),
    ("南瓜花", "pumpkin_blossom"),
    ("丝瓜花", "loofah_flower"),
    ("槐花", "sophora_flower"),
    ("桂花", "osmanthus"),

    # ==================== 豆制品类 ====================
    ("豆腐", "tofu"),
    ("豆腐干", "dried_tofu"),
    ("豆腐皮", "tofu_skin"),
    ("腐竹", "bean_curd_sticks"),
    ("千张", "tofu_sheets"),
    ("油豆腐", "fried_tofu"),
    ("臭豆腐", "stinky_tofu"),
    ("豆腐乳", "fermented_tofu"),
    ("纳豆", "natto"),
    ("豆豉", "fermented_black_beans"),

    # ==================== 芽苗类 ====================
    ("豌豆苗", "pea_shoots"),
    ("萝卜苗", "radish_sprouts"),
    ("苜蓿芽", "alfalfa_sprouts"),
    ("花生芽", "peanut_sprouts"),
    ("香椿", "chinese_toon"),
    ("枸杞芽", "goji_sprouts"),

    # ==================== 水生蔬菜 ====================
    ("莼菜", "water_shield"),
    ("水芹菜", "water_parsley"),
    ("藕带", "lotus_sprout"),
    ("菰米", "wild_rice"),
    ("蒲菜", "cattail_shoots"),

    # ==================== 野菜类 ====================
    ("香椿芽", "toon_sprouts"),
    ("灰灰菜", "lambs_quarters"),
    ("车前草", "plantain_herb"),
    ("地皮菜", "ground_ear"),
    ("婆婆丁", "dandelion_herb"),
    ("扫帚菜", "kochia"),
    ("面条菜", "noodle_vegetable"),
    ("苦菜", "bitter_herb"),
    ("刺嫩芽", "aralia_sprouts"),
    ("蕨菜", "bracken"),

    # ==================== 调味蔬菜 ====================
    ("花椒", "sichuan_pepper"),
    ("八角", "star_anise"),
    ("桂皮", "cinnamon"),
    ("草果", "tsaoko"),
    ("白芷", "angelica"),
    ("陈皮", "dried_tangerine_peel"),
    ("香茅", "lemongrass"),
    ("迷迭香", "rosemary"),
    ("百里香", "thyme"),
    ("罗勒", "basil"),
    ("牛至", "oregano"),
    ("月桂叶", "bay_leaf"),
    ("柠檬草", "citronella"),

    # ==================== 腌制/干货蔬菜 ====================
    ("榨菜", "preserved_mustard"),
    ("梅干菜", "preserved_dried_vegetable"),
    ("萝卜干", "dried_radish"),
    ("笋干", "dried_bamboo_shoot"),
    ("干辣椒", "dried_chili"),
    ("干香菇", "dried_shiitake"),
    ("紫菜", "nori"),
    ("海带", "kelp"),
    ("裙带菜", "wakame"),
    ("石花菜", "agar_seaweed"),
    ("发菜", "fat_choy"),
    ("粉丝", "glass_noodles"),
    ("粉条", "sweet_potato_noodles"),
    ("腐乳", "fermented_bean_curd"),
    ("马兰头", "indian_aster"),
    ("豆苗", "bean_seedlings"),
    ("芥菜头", "kohlrabi_mustard"),
]

# 确保刚好 200 个
assert len(VEGETABLES) == 200, f"当前数量: {len(VEGETABLES)}, 需要 200 个"
